# Compiled with 0.30.1 rules

# Don't add any files/directories to the 'include:' section. Everything not
# listed under 'excluded:' should be linted.
# included:
#   - Nothing

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

## Rules

# enabled_rules_for_documentation:
#   - attributes
#   - block_based_kvo
#   - class_delegate_protocol
#   - closing_brace
#   - closure_end_indentation
#   - closure_parameter_position
#   - closure_spacing
#   - colon
#   - comma
#   - compiler_protocol_init
#   - contains_over_first_not_nil
#   - control_statement
#   - custom_rules
#   - discarded_notification_center_observer
#   - discouraged_direct_init
#   - duplicate_imports
#   - dynamic_inline
#   - empty_parameters
#   - empty_parentheses_with_trailing_closure
#   - fallthrough
#   - file_length
#   - first_where
#   - force_cast
#   - force_try
#   - force_unwrapping
#   - generic_type_name
#   - is_disjoint
#   - identifier_name
#   - inert_defer
#   - implicit_getter
#   - implicitly_unwrapped_optional
#   - leading_whitespace
#   - legacy_cggeometry_functions
#   - legacy_constant
#   - legacy_constructor
#   - legacy_hashing
#   - legacy_nsgeometry_functions
#   - mark
#   - nesting
#   - notification_center_detachment
#   - no_fallthrough_only
#   - object_literal
#   - opening_brace
#   - operator_usage_whitespace
#   - operator_whitespace
#   - private_outlet
#   - private_unit_test
#   - protocol_property_accessors_order
#   - redundant_discardable_let
#   - redundant_nil_coalescing
#   - redundant_objc_attribute
#   - redundant_optional_initialization
#   - redundant_set_access_control
#   - redundant_string_enum_value
#   - return_arrow_whitespace
#   - statement_position
#   - superfluous_disable_command
#   - switch_case_alignment
#   - syntactic_sugar
#   - trailing_comma
#   - trailing_newline
#   - trailing_semicolon
#   - trailing_whitespace
#   - type_body_length
#   - type_name
#   - unneeded_break_in_switch
#   - unused_closure_parameter
#   - unused_control_flow_label
#   - unused_enumerated
#   - unused_optional_binding
#   - unused_setter_value
#   - valid_ibinspectable
#   - vertical_parameter_alignment
#   - vertical_whitespace
#   - weak_delegate
#   - xctfail_message

opt_in_rules:
  - anyobject_protocol
  - closure_body_length
  - collection_alignment
  - convenience_type
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nslocalizedstring_key
  - overridden_super_call
  - prohibited_super_call
  - redundant_void_return
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - unavailable_function
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher

disabled_rules:
  - array_init
  - conditional_returns_on_newline
  - cyclomatic_complexity
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_enum_arguments
  - empty_string
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_name
  - for_where
  - implicit_return
  - let_var_whitespace
  - missing_docs
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_over_fileprivate
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_imports
  - shorthand_operator
  - strict_fileprivate
  - switch_case_on_newline
  - todo
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - void_return
  - yoda_condition

  # These next rules are recommended to be enabled on a project-by-project
  # basis with specific configurations that fit the project style.
  - function_body_length
  - function_parameter_count
  - large_tuple
  - last_where
  - line_length
  - literal_expression_end_indentation
  - modifier_order
  - multiple_closures_with_trailing_closure
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

## Rule Configuration

colon:
  apply_to_dictionaries: false

file_length:
  warning: 750
  error: 1500

identifier_name:
  excluded:
    - id

lower_acl_than_parent:
  severity: error

nesting:
  type_level: 3
